wballard/starphleet

- scripts/tools
- BUG: If an order is unpublished it is currently still grabbing the GIT repo
from the previous order that is processed by starphleet_monitor_orders.
This occurs because the run_orders function in 'tools' echos the git
repo into /tmp/$$ [pid] for autodeploys but does not clear out this file
if the order is unpublished.  Thus, the next few lines of code in starphleet_monitor_orders 
still detect a ${REMOTE} and grabs the git repo from the previous processed autodeploy.
- FIX: This change clears out the /tmp/$$ for unpublished order files.  I think
this should prevent unpublished orders from grabbing the wrong
GIT repo
> Bug Fix - "Unpublished" Orders Grabbing Wrong Git Repo

- scripts/starphleet-containermake
- scripts/starphleet-lxc-ssh
- scripts/starphleet-public-keys
- scripts/tools
starphleet-lxc-ssh is a new file that takes as arguments an order name and optional a command to run on the container.
starphleet-containermake changes are to mount the ships /home/admiral and create just the folder /home/admiral on the new container. Also, on the new container we add the admiral user since the containder will not have a uid for admiral when we chown the folder. 
In tools we create a private/public key that we then cat to the auth file.
> allow admiral to ssh to any container as admiral

- scripts/starphleet-publish
allows one of my services to call http://localship/foo w/o authenticating, but requests from outside the 10.0.3.x network still need to go through ldap
> ldap work around for other containers on the ship

- scripts/starphleet-publish
This bug was manifested by the beta rewrite rules.  In a case where you were in a beta for the following service/endpoint things work fine:
*.domain.com/someservice/endpoint
However, the rewrite rules for the above beta group would also match:
*.domain.com/someotherservice/someservice/endpoint
This will 'break' the above url for anything pointing to _url_/someservice/_endpoint_.  The below should anchor the rewrite rules for a beta to the service they are intended.
> Bug: Make rewrite rules be tied to root path

- overlay/etc/init/starphleet_serve_order.conf
I'd like to hook up a healthcheck $thing.  The healthcheck may run within a container.  
When querying the orders files for healthchecks, I'd like to then run that healthcheck directly against the containers IP address.  I'm going to get that ip from .starphleetstatus.ip and would like the port as well.
> Also save the port the service was exported on

- scripts/starphleet-publish
- scripts/starphleet-redeploy
Since unpublished orders do not have a git repo - only removing the non-existent repos does not trigger a redeploy of unpublished orders.
Removing the ".orders_sha" does cause an "unpublished" to redeploy.
> Bug - starphleet-redeploy does not trigger deploy for unpublished orders

- scripts/starphleet-expose
If someone were to accidentally expose port '10' this would accidentally match the MASQ rule assigned to the 10.0.3.* subnet.  The iptables command that purges PREROUTING rules will only run against the 'PREROUTING' table but would cause an error on a rule number that doesn't exist in that table.  By grepping for only DNAT rules we can avoid this accident.
> Only list DNAT rules

- scripts/starphleet-reaper
- Using a regex for container matching needs a ^ in front.  Otherwise,
service name like jtapi also matches a service name of
'pi-[sha]-[sha]' when you're trying to reap 'pi'
- Start using starphleet-launcher
> Bug:  Reaping wrong containers

- scripts/starphleet-attach
- When using 'starphleet-attach' I conjecture most of the time we want
to be logged in as the user in which apps run.  Pass the command
"su - ubuntu" into the attach to simulate a login as 'ubuntu'
> Attach as "ubuntu" user

- scripts/starphleet-install
Local vagrant install won't work unless apt-get update and apt-get upgrade are run before the initial apt-get installs.
> add apt-get update/upgrade to install script so it works locally

- scripts/starphleet-publish
- Give the container the service name
- Previous commit only announced the container name but we want it to make it into the container
> Pass the service name (order) through

- scripts/starphleet-publish
- Either need to specify /24 - or fix subnet
Example:
2015/03/19 17:28:34 [warn] 17597#0: low address bits of 10.0.3.0/8 are
meaningless in
/var/starphleet/nginx/published/%22%2Fsp-preview%22.conf:25
2015/03/19 17:28:34 [warn] 17597#0: low address bits of 10.0.3.0/8 are
meaningless in /var/starphleet/nginx/published/%22%2Fspquery%22.conf:25
2015/03/19 17:28:34 [warn] 17597#0: low address bits of 10.0.3.0/8 are
meaningless in
/var/starphleet/nginx/published/%22%2Fswitchboard%22.conf:25
2015/03/19 17:28:34 [warn] 17597#0: low address bits of 10.0.3.0/8 are
meaningless in
/var/starphleet/nginx/published/%22%2Ftaxonomizer%22.conf:25
2015/03/19 17:28:34 [warn] 17597#0: low address bits of 10.0.3.0/8 are
meaningless in
/var/starphleet/nginx/published/%22%2Ftrackingexpress%22.conf:25
2015/03/19 …
> Make nginx logs less noisy

- overlay/etc/logrotate.d/rsyslog
- overlay/etc/starphleet
- scripts/starphleet-install
- scripts/starphleet-launcher
- scripts/tools
- webinstall
Example:
- bash -c "$(curl -s https://raw.githubusercontent.com/wballard/starphleet/master/webinstall)"
- [Upload Key]
This commit will fully configure EC2 drives on the machine and mount them appropriately.  Priority is given in the following order for mountable devices:
/dev/xvdb -> /var/lib/lxc
/dev/xvdc -> /var/starphleet
/dev/xvdd -> /var/log
If a drive is not found because one is not available it is simply ignored.
Slight modifications were made to starphleet-launcher because it would only work if the commands were in /usr/bin and not on a clean installation.  Please review.. I'm sure I did it wrong.  =)
> Install Starphleet on EC2 and auto deploy disks:

- Vagrantfile
$base_provision_script getting called over-and-over.. which re-installs starphleet each time.
> Don't run the re-install routine over-and-over

- scripts/starphleet-orphan-reaper
- In production checking for the orders directory is not enough since we
checkout git dirs into that directory.  In this case, the directory is
not empty when git tries to remove it so they stay around.  Moving to
checking for the orders file specifically.. and then cleaning up
${CURRENT_ORDERS} and ${HEADQUARTERS_LOCAL} when appropriate
> Bug Fix - Orphan reaper needs to check for orders

- overlay/etc/logrotate.d/upstart
Step one - isolate the nginx logrotate to allow nginx log retention.
Often need the nginx logs to lookup called traffic and validate user agents/time of requests.
> Split out the nginx log to retain more traffic

- scripts/starphleet-beta-groups
- scripts/starphleet-cleanup
- scripts/starphleet-publish
- Pull beta configuration out of starphleet-publish completely.
- All beta configuration occurs in monitor_headquarters and is
completely rebuilt each time starphleet-beta-groups is called
- for:igroff@glgroup.com
> Centralize all beta configuration

- overlay/etc/init/starphleet_monitor_orders.conf
- scripts/starphleet-orphan-reaper
- Bug: ".starphleetstatus" is not a symlink - so this code never ran
- Bug: Testing if an orders dir exists isn't good enough for validating
if the orders are stale.  Because the orders directory in hq
contains a git repo that gets checked out, when the orders go away, git
does NOT purge the directory.  Thus, you must test for the actual orders
file
- Bug: Need to remove stale beta files
- for:igroff@glgroup.com
> Bug: Clean up published nginx configs

- scripts/starphleet-beta-groups
Users on betas getting improperly rewritten to outer space.  The rewrite rules were missing the service name.
Missing slash and var name wrong
> Bug: Beta group re-write rule broken

- scripts/starphleet-install
- scripts/tools
The intended behavior of /etc/starphleet is that it is static and comes directly from starphleet's code base.  There are times we want machine specific configs or may want to override starphleet's configs.  We don't want our changes to be overridden by a subsequent perform-overlay.  
During install:
- create /etc/starphleet.d
- have /usr/bin/tools source /etc/starphleet.d/* AFTER /etc/starphleet
> Machine Specific Configs

- overlay/etc/init/starphleet_serve_order.post-start
- When a container builds successfully, we were reaping the old
before
exposing the new one.  This creates a period of time where the
intended exposed port is orphaned.  Especially if the reaper takes
a while.
> Migrate the expose above the sleep

- scripts/starphleet-install
- scripts/tools
- The dir /etc/starphleet.d gets created on new installs.  However, if a
file doesn't exist in that directory then the new code for
starphleet.d runs with an error (no files found).  Scripts with set -e
die on that.  All sorts of weird things happen
> Bug: Files not existing in starphleet.d hurt set-e

- overlay/etc/init/starphleet_monitor_remotes.conf
User Jeff O'Connell reported remotes are getting overridden in dev_mode even after initial checkout.
> Remote devmode one checkout

- overlay/etc/init/starphleet_monitor_orders.conf
If the user comments out the 'autodeploy' line it creates a condition in which dev_mode does not respect the appropriate behavior and generates a broken container.
> Bug: Do not deploy commented autodeploys in dev_mode

- overlay/etc/init/starphleet_serve_order.post-start
- Fallback to previous behavior of re-checking a container
over-and-over.  After observing several long-init'ing containers this
is the more ideal behavior
- Move all healthcheck logic into one place for read-ability
- Add ability for orders to tweak healthcheck behavior
via HEALTHCHECK_INIT_DELAY
> Fallback to looping healthchecks on publish

- scripts/starphleet-install
- LXC subnet changes modify default system files which causes install to prompt
for override.  I don't see a logical reason not to install the
packages earlier in the install.  This fixes production installs and
vmware now works again.  No prompts since we update the config after
the package completes
> Bug: install packages before config changes

- scripts/starphleet-reaper
- We don't want to reap if the status file is 'newer' than container
indicating the container never published
- Proper support for a 'force' reaping
> Bug: Logic error

- overlay/etc/init/starphleet_nginx_hupper.start
- overlay/etc/starphleet
- scripts/starphleet-dns-offline
- scripts/starphleet-dns-online
- The starphleet-dns-online/offline commands need to support the new
concept of the hupper doing all-the-things for configuration nginx.
> DNS Online/Offline support for new hupper

- overlay/etc/init/starphleet.conf
- scripts/starphleet-cleanup
- In devmode, vagrant halt doesn't always allow starphleet to shutdown
cleanly.  Thus, files don't get cleaned up correctly. Run a cleanup
before starting up starphleet as well
> Run starphleet-clean on pre-start

- overlay/etc/init/starphleet_monitor_orders.conf
- overlay/etc/init/starphleet_monitor_orders.start
- Running in a continuous loop allows order files that set things like
PATH to consantly append to the path on each loop.  This can
eventually drain all resources.  Dropping out of the looping pattern and
allowing upstart to restart the job makes the script more resilient to
leaking
- The list of changes shown in the file are misleading.  The script was modified to adjust for the lack of loop in the indentation.
> Monitor orders can leak memory

- overlay/etc/init/starphleet_serve_order.post-stop
- scripts/starphleet-reaper
- Successful reaps of a container imply a newer and working container is
up and we would no longer need to reference the previous build logs.
Thus, we are now going to reap the old logs
> Remove build logs when a container is reaped

- scripts/starphleet-stop
- Running lxc-stop isn't enough since the respawn in serve_order will
override your intentions.  Stop in upstart instead
> Change the stop behavior for starphleet-stop

- overlay/etc/starphleet
- Allow making /var/data huge and also filling up /var/data won't impact
the functionality of the machines
> Make /var/data separate from /var/lib/lxc

- overlay/etc/init/starphleet_serve_order.post-start
- overlay/etc/init/starphleet_serve_order.pre-start
- Need to support new --force for orders with 'stop_before" since the
normal reap condition now guards against reaping containers still
running by default
> Need a force reap when called for a stop

- scripts/starphleet-publish
Allow the redirect for a service to be set by a cookie.  For instance:
- Make a cookie named beta_serviceName
- Set value to betaName
User will silently get redirected from /serviceName to /betaName
This implementation may seem counter intuitive.  It works around NGINX not supporting hyphens in the $cookie variable inside rewrite rules.  The $cookie variable with hyphens does work within an `if` condition.  More details here:
http://bit.ly/1UQuC67
> Support App Beta Cookies

- overlay/etc/init/starphleet_serve_order.post-start
- Logic error was not running through all healthcheck attempts
- Bug in condition to punt if tries eventually fail which would allow
code to fall through and deploy an unhealthy container
> Bug: Don't deploy unhealthy containers

- overlay/etc/cron.daily/restart_nginx
- overlay/etc/init/starphleet_nginx_hupper.start
- overlay/etc/starphleet
- scripts/starphleet-restart-nginx
The main NGINX process on the host OS will hold open workers for websockets.  If the websockets never disconnect the nginx processes are "leaked" until all websockets close.  Over time, this can creep towards the max number of NGINX threads nginx will start.  This patch adds the ability to trigger a safe NGINX restart (using the starphleet-nginx-hupper).  It also adds a cron job to run the restart once per day.
> Support Restart of NGINX in Hupper

- scripts/starphleet-attach
- Assume the user knows what they are doing.  lxc-ls -f is expensive
with a ton of running containers.  It makes this handy command too
slow and the 'running' check doesn't gain much
> Remove the 'fancy'

- overlay/etc/init/starphleet_monitor_orders.start
- overlay/etc/init/starphleet_nginx_hupper.start
- scripts/starphleet-publish
- scripts/tools
Support for the publish command.  The publish command allows us to deploy a single instance of an app but 'publish' that app at multiple locations.  For instance this endpoint is deployed:
/example1
In the orders file for /example2 and /example3 put "publish /example1".  
Starphleet will deploy /example1 once and create configs for /example2 and /example3 that point directly to the container of /example1
> Publish Command

- overlay/etc/starphleet
- Buildpacks have the port variable overwritten from the setting in the
orders file.  This change will respect the orders if the variable is
set but still fallback to having a default
> Respect port if set

- scripts/starphleet-publish
This commit breaks starphleet.  I'm trying to deploy production servers and can't worry about fixing right now.  Here are the errors.  
3/17/16 01:09:44 - autodeploy from git@github.com:glg-core/mosaic-mongo.git#master
nginx: [emerg] unknown directive "Path=/cerca" in /var/starphleet/nginx/published/cerca.conf:31
nginx: configuration file /var/starphleet/nginx/nginx.conf test failed
03/17/16 01:09:44 - nginx configuration fails validity test, will not restart or apply configuration changes
nginx: [emerg] unknown directive "Path=/cerca" in /var/starphleet/nginx/published/cerca.conf:31
nginx: configuration file /var/starphleet/nginx/nginx.conf test failed
mail: Null message body; hope that's ok
> Revert breaking cookie change

- scripts/tools
Allow a machine-level environment override to be primary over a global HQ.  That allows the refinement of configurations to go from:
Global -> Machine -> Orders
> Allow local machine envs to override the HQ

- overlay/etc/starphleet
- scripts/starphleet-devmode-update-local-ip
- vmware
- Grab First iface ip address for passing host info in local mode
- Unset default security modes instead of setting to empty
- Bug kills VMWare Fusion
Promisc mode for sniffers will kill the entire virtual machine.
Hopefully this fixes issue for mac users:
https://github.com/coreos/coreos-vagrant/issues/123
> Bug that kills VMWare Fusion

- Vagrantfile
this allows use of `/hosthome/.ssh` keys from the vm, even if the key requires a passphrase.
only requirement is that the passphrase has been previously decrypted on the host machine, and stored in something like the osx keychain.
> ssh agent forwarding from host machine to vm

- Vagrantfile
- overlay/etc/init/starphleet_monitor_headquarters.start
- overlay/etc/init/starphleet_monitor_orders.conf
- overlay/etc/init/starphleet_monitor_orders.start
- overlay/etc/init/starphleet_monitor_remotes.start
- overlay/etc/init/starphleet_serve_order.conf
- overlay/etc/init/starphleet_serve_order.pre-start
- overlay/etc/starphleet
- scripts/builder
- scripts/starphleet-cleanup
- scripts/starphleet-containerize
- scripts/starphleet-containermake
- scripts/starphleet-devmode-update-local-ip
- scripts/starphleet-git-synch
- scripts/starphleet-headquarters
- scripts/starphleet-install
- scripts/starphleet-reaper
- scripts/starphleet-redeploy
- scripts/starphleet-status
- scripts/tools
- virtualbox
- vmware
- webinstall
* Devmode is now an environment configuration
* Devmode primarily now prevents git-synchs from overriding existing files
* Core files no longer go over HGFS (huge performance gains / Using NFS instead)
* Allows HQ modification on Host OS  
* No longer has buggy interactions with HGFS.  
* Install now syncs to "Starphleet Host" instead of going over HGFS
* Make HOST OS ip exposed during vagrant up automatically
* Make starphleet_serve_order never give up
* Remove concept of Pub Key (Vagrant does not need)
* Fixes link to VIrtualBox Image
* Fix hostmanager config in Vagrantfile
* Fixes networking on VirtualBox 
* Remove concept of 'publish'
* VirtualBox now supported (./virtualbox init scripts helper)
* slim up dev_mode code in starphleet_monitor_orders
* Make starphleet-headquarters use …
> Devmode overhaul

- scripts/starphleet-publish
The slash in this path was not intended to be removed.
> Bug:  Fix slash missing in path for cookie betas

- scripts/starphleet-status
- By passing the Authorization Header - We can still run a HEAD against
the real target container and determine where NGINX is pointing.
Without this header, a JWT container would respond with the auth login
app
> Pass an Authorization Header in status command

- overlay/var/starphleet/nginx/lua/jwt.lua
- Pass the JWT Secret from the redirected container so JWT does not have
to depend on multiple login apps
> Pass the secret from the parent container

- overlay/var/starphleet/nginx/lua/jwt.lua
- Allow a caller to leave the JWT token in the URL when making calls to
Starphleet.  This will allow callers to not require the Cookie
mechanism
> Disable JWT redirect with URL Parm

- overlay/etc/init/starphleet_nginx_hupper.start
- The file being purged actually affects the live server.  Thus, we'll
just have to allow clutter in this folder but not purge
> Bug:  htpasswd is not cached

- overlay/var/starphleet/nginx/lua/jwt.lua
- When a user changes their identity by passing a url token, if the
token is expired, we currently fall through and would support their
session cookie still.  Instead, if an identity change is being
requested, even with an expired token, we will at least prompt for auth,
which will allow the user to log back in as themselves.
- This fixes a scenario where you are logged in as someone else and are
unable to click an old link to login as yourself to get back into your
own identity
> Feature: Prompt for Auth on JWT Identity Change

- nginx/Makefile
- fixes glg/Firefighting#132
- https://www.openssl.org/news/secadv/20160926.txt
> Update to the latest openssl:

- overlay/var/starphleet/nginx/proxy.conf
- Prevents simple file uploads > 10m.  Bumping to support larger sizes.
> Bump Max Body Size

- scripts/starphleet-publish
- There are instances where Starphleet might be running on a private
network intentionally and you might not want auto auth enabled
> Allow "auto" auth to optionally be disabled

- scripts/starphleet-publish
This fixes the issue where JWT containers reap the active container before the new container is available.  The reaper will now correctly see that the active container is being pointed out and not reap until it's appropriate.
> Bug: Fix local healthchecks

- scripts/cronner
- scripts/runner
Adding double brackets around log tags for jobs.  This will make it easier to pullout service name and job name, as well as to ignore log entries that are duplicates or irrelevant.
> Delimit tags with double brackets for easier log parsing

- overlay/etc/modprobe.d/netfilter.conf
- overlay/etc/sysctl.d/100-starphleet.conf
- Reduce instances of these errors:
```
obs kernel: [38775494.392631] nf_conntrack: table full, dropping packet
Feb 23 16:44:36 jobs kernel: [38775494.393661] nf_conntrack: table full,
dropping packet
Feb 23 16:44:36 jobs kernel: [38775494.494836] nf_conntrack: table full,
dropping packet
Feb 23 16:44:36 jobs kernel: [38775494.495169] nf_conntrack: table full,
dropping packet
Feb 23 16:44:36 jobs kernel: [38775494.495196] nf_conntrack: table full,
dropping packet
```
> Bump up nf_conntrack

- overlay/var/starphleet/nginx/lua/jwt.lua
- When a user is met with a hard 403 it adds confusion
to the user experience.  Allow the login app to handle
this condition in a way that makes sense for the
business.  Instead of a hard 403 we pass along a header
that lets the app decide if it wants to 403 or re-login
the user.  We still do _not_ allow the user to access
the page by setting the token to nil
> Pass "access denied" behavior to the login app

- overlay/var/starphleet/nginx/lua/jwt.lua
- When a user is met with a hard 403 it adds confusion
to the user experience.  Allow the login app to handle
this condition in a way that makes sense for the
business.  Instead of a hard 403 we pass along a header
that lets the app decide if it wants to 403 or re-login
the user.  We still do _not_ allow the user to access
the page by setting the token to nil
> Pass "access denied" behavior to the login app (#362)

- overlay/etc/starphleet
- overlay/var/starphleet/containers/starphleet-base
- scripts/tools
This builds on the `secrets` function provided by @bhudgens. We have created a function `fromJson` that handles extracting one field from a json object, rather than having that functionality directly inside of `secrets`. This allows us to conveniently request a whole secret, and then assign its components to different env variables.
Usage:
```shell
fromJson '{"somekey": "somevalue"}' somekey
```
This is pretty similar to `jq`, except much less complex/complete, and has no dependencies beyond bash and python
We also wrote a function to get region from instance metadata if it can't be found in env or ~/.aws
Usage:
```shell
getRegionFromInstanceMetadata
```
So, all together, usage of secrets looks like:
```shell
SMASH_SECRET=$(secrets SMASH)
export …
```
> Add secrets

- overlay/var/starphleet/containers/starphleet-base
- scripts/tools
This makes a minor change regarding caching the AWS region the first time we request it, as opposed to requesting it for every single secrets retrieval. The prior behavior resulted in occasionally not getting the region, and then failing subsequent requests. This has been tested on a dev ship.
> caches region from instance metadata, update aws-cli

- scripts/starphleet-containerize
This fixes glg/secrets#20.
Now, starphleet will fetch the latest secrets binary from s3 each time it builds a new container, and not just in the base container. This finishes out the ci/cd pipeline such that all new containers will always be running whatever is in `master` in glg/secrets.  
This was tested on @drhayes devship.
> Download latest secrets binary in starphleet-containerize

- scripts/starphleet-redeploy
While debugging with Ben, we realized this should be in double quotes.
> should be double quotes

- scripts/mount-block-devices
- scripts/starphleet-install
Nobootwait was removed as an option in Ubuntu 16. This causes the drives
to fail to mount. Tested the change on a devDB install using Ubuntu 16
successfully.
Issue: https://askubuntu.com/questions/786928/ubuntu-16-04-fstab-fails-with-nobootwait
> Remove nobootwait fstab option

- scripts/starphleet-containerize
The region arg is as much a part of the path as the bucket name.
> Add region argument to aws s3 call to download secrets binary.

- scripts/starphleet-containerize
Ensuring that jq is in every container will give devs more flexibility when dealing with json secrets, and provides a universally available solution (as opposed to `fromJson` which is starphleet specific). This way they can learn one workflow for secrets, whether working locally, dev ship, production, jobs, etc.
> Guarantee JSON functionality along with secrets

- overlay/var/starphleet/nginx/lua/jwt.lua
- scripts/starphleet-publish
The starphleet-publish was modified to add another variable called jwt_auth_required that will allow support of auth0. This variable is read in the jwt.lua file and there are 2 scenarios:
1. User does not have a token and auth is required so set header.
2. User does have a valid token and the new acr jwt claim is not set.
> Changes to provide auth0 support
