wballard/starphleet

scripts/packages
Make NTP one of the default packages for starphleet.
=> Add NTP as default package for Starphleet

scripts/starphleet-beta-groups, scripts/starphleet-publish
=> Beta group uniq issue

scripts/starphleet-publish
- if the corresponding beta user file doesn't exist skip the conf
for nginx
=> Don't create a conf for a non-existing beta

scripts/packages, scripts/starphleet-attach, scripts/starphleet-publish
Script to make attaching to instances easier.
=> Starphleet attach

scripts/starphleet-containermake
- rbind /var/data in containers so sub-mounts are reachable
- make the /var/starphleet root read only
=> Change mount configs for LXC Containers

scripts/starphleet-publish
Bug:  Using wrong variable for HQ path.
=> Bug - Wrong variable for hq path in starphleet-publish

scripts/starphleet-publish
- Allow region->region communication to bypass auth
=> Allow no auth from regions

scripts/starphleet-launcher
- Ian would like all commands to be outputted so we can cut-and-paste
=> Trace output all commands

scripts/starphleet-publish
- No sha business.  Just the name
- Fixes #196
=> Send service name as requested

overlay/etc/init/starphleet_serve_order.conf
These need to be renamed as well
=> Ian requested we don't use .sh

scripts/starphleet-retry-deploy
- Try to deploy a service utilizing the built-in mechanisms of
starphleet - BUT - the container will only go live if it succeeds like
a normal container would.  If a new sha is retreived from GIT or the
ORDER SHA - this container will get reaped as expected.
=> Retry-Deploy

scripts/starphleet-install, scripts/starphleet-publish
- If the machine has a STARPHLEET_REGION variable set, output that
variable in NGINX
- When starphleet-install runs - if a region is detected (IE, running in
EC2) then we add that config to the ships variables
=> Add a ship header

scripts/starphleet-retry-deploy
=> Add warning about shas - per the Groff

index.md
Local development mode documentation.
=> Devmode Documentation

index.md
=> Documentation for Access Control Lists

scripts/starphleet-nginx-acl-rules
The ACL files cannot contain dupes in the map files.  Protect against that
=> Uniq the acl files

webinstall
- Make it possible to override webinstall variables before you run it
=> Make it easy to override web install script parms

scripts/starphleet-nginx-acl-rules
=> Handle NGINX being case insensitive

scripts/starphleet-containermake
Allow containers and orders to respect the starphleet.d dir
=> Copy the starphleet.d dir to the container

scripts/starphleet-reaper
=> Bug:  Missing dolar sign

scripts/starphleet-orphan-reaper
Force flag should be used when reaping orphans
=> Support new 'force' flag when reaping orphans

overlay/var/starphleet/nginx/nginx.conf
Break out nginx logs and error logs
=> NGINX change to where access logs live

scripts/starphleet-status
- Adds support for multi-container statuses
- Add nginx container output
- Support the previously orphaned --metadata info
=> Tidy Up starphleet-status

overlay/etc/init/starphleet_monitor_remotes.start, provision/patch
- Need to make tools available in function declaration
- Make provision script restart remotes
- fixes wballard/starphleet#253
=> Fix remotes overriding in dev_mode

scripts/starphleet-publish
- The orders file may change ports but we want to publish to the correct
port for the container
=> Respect the status file for port - NOT the orders.

scripts/starphleet-publish
- Add other RFC1918 address range
- Add the bypass for both ldap and http scenarios
=> Fix Bug Where Auth Bypass doesn't work htpasswd

overlay/etc/init/starphleet_monitor_orders.start
- Add unpublished support for devmode
=> Support UNPUBLISHED in devmode

scripts/starphleet-expose
Need UDP support in expose for SYSLOG forwarding
=> Expose needs to support UDP also

index.md
minor update to the documentation that we missed earlier.
=> document the JWT_EXPIRATION environment var

scripts/tools
- aside from /var/lib/lxc/data we want to disable journaling
=> Disable journaling

scripts/starphleet-publish
Addresses issue #284 
Not critical, but a bit annoying.  Let's not create a cookie in the browser for every unique path to a starphleet app.
=> Cookie path

overlay/etc/init/starphleet_monitor_orders.start, overlay/etc/init/starphleet_nginx_hupper.start, overlay/etc/starphleet, scripts/starphleet-publish, scripts/tools
Use env vars for security
This PR is for sharing
=> Remove files for security - Move Security Concepts to ENV Vars - Allow Default Policy

vmware_hgfs_fix.sh
=> Patch for latest vmware version

scripts/tools
- Reported bug that symlink was failing after reboot
- Fixes #294
=> Be defensive about creating the symlinks

Vagrantfile, scripts/starphleet-devmode-update-local-ip
Make the HOST IP address available to the Starphleet HOST and Containers
=> Pass the HOST IP Address to the Starphleet HOST

scripts/starphleet-reaper
Should kill the healthcheck on a reap.
=> Kill the HC also

scripts/starphleet-publish
- Always auth in dev_mode
- Remove legacy bad network configs
=> Always auth in devmode

overlay/var/starphleet/nginx/lua/guard.lua, scripts/starphleet-publish
- Use the override system for defaults and only have one expiration
=> Just use one JWT expiration

scripts/packages, scripts/tools
- Fix grep bug so reboots work
- Install some debug tools during install
=> Fix bug in ec2_mounts

scripts/starphleet-reaper
The reaper should check for the container name with case insensitivity
in case the keys change
=> Change: Make reaper check header with case insensitivity

nginx/Makefile
- Convert to Variable
- Make sure variable used in all locations of version change
=> Bug: Not all locations of SSL version changes

overlay/etc/starphleet, scripts/starphleet-beta-groups, scripts/starphleet-install, scripts/starphleet-public-keys, scripts/tools
- Allow for a "Captain" user with reduced privs
- Allow for Beta Configs to be disjoined from the HQ
=> Captain User - Remote Beta Configs

overlay/etc/init/starphleet.pre-start
- Setting INTERNAL_HOST as part of image
=> Set the INTERNAL_HOST

overlay/etc/starphleet
Adds support for a new AWS drive type
=> Support nvme drives

scripts/starphleet-healthcheck
- If the HC sees a 401 .. we can assume the container is also healthy
- Fixes ACL containers
=> Make Healtcheck More flexible

scripts/runner
- Copy the script local to container
- Set +x
- Run from local location
=> Make Cron Permission Handle Execute Of Crons

scripts/starphleet-healthcheck
We found a service that was accepting connections, however the service would not respond to requests.
=> include response timeout in addition to connection timeout

scripts/starphleet-git-synch
- I have evidence that sometimes git will not branch switch
admiral@services[us-east-1e]:/var/starphleet/headquarters/mosaic/git$ sudo git checkout jobs
admiral@services[us-east-1e]:/var/starphleet/headquarters/mosaic/git$ sudo git branch
* master
- We'll avoid it and reclone instead
=> Bug: Git fails on branch changes sometimes

scripts/starphleet-containerize
Reverts wballard/starphleet#385
=> Revert "Guarantee JSON functionality along with secrets"

overlay/var/starphleet/nginx/lua/jwt.lua
- There is no reason to do a replace here.  We can just send
the user to the auth site
=> Only send user to auth site

scripts/starphleet-containerize, scripts/tools
Get Secrets on sixteen-oh-four branch of Starphleet. [I spoke with David Hayes and Shawn and only need a few changes](https://teams.microsoft.com/l/message/19:9a58c129d3654d7c96edac1ec7f3cc51@thread.skype/1554744388210?tenantId=ce6e7548-545e-40c2-b32d-a76b6acc9c2e&groupId=36384efe-bc19-4d9d-a5d2-37e595c37ebb&parentMessageId=1554744388210&teamName=GLG%20Engineering&channelName=MetaDevops&createdTime=1554744388210)
My only concern is launching this while the current mosaic machines are pointed at this branch. I assume that the current mosaic will just download the executable - so really no harm.
=> add secrets

overlay/etc/init/starphleet_serve_order.conf, scripts/tools
- This change shifts build logs to syslog and frees up file handles in
init
=> We are running out of file handles on servers

overlay/etc/init/starphleet_serve_order.conf
Please send refund of 8 hours of my time to....
we have confirmed that these changes fix the failure behavior we encountered on our new prod ships.
=> handle failures inside of pipelines

overlay/var/starphleet/containers/starphleet-base
Done similarly in 'services' phleet here https://github.com/wballard/starphleet/commit/b99139c70c4c7ca18107e2391299e9411dadc0b4
=> Pin bundler version - Mosaic is breaking.

scripts/tools
This adds from `fromJson` utility to the version of starphleet deployed on the search phleet.
=> add fromJson to tools
